name: Bulid and run tests
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build compilation DB
        run: |
          mkdir build
          pushd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=true ..
          popd
          ln -sv build/compile_commands.json .

      - name: Check formatting
        run: clang-format-18 --dry-run --Werror server/*
      - name: Check linting
        run: clang-tidy-18 '--warnings-as-errors=*' server/*

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run unit tests
        run: cmake --build build --target test
