name: Bulid and run tests
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install BEAR tool
        run: sudo apt-get install bear
      - name: Build compilation DB
        run: make compile-commands

      - name: Check formatting
        run: make format-check
        env:
          CLANG_FORMAT: clang-format-18
      - name: Check linting
        run: make check
        env:
          CLANG_TIDY: clang-tidy-18

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        run: make all
      - name: Run unit tests
        run: make unit-test
      - name: Run E2E tests
        run: make e2e-test
