name: Bulid and run tests
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: make format-check
      - name: Check linting
        run: make check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        run: make all
      - name: Run unit tests
        run: make unit-test
      - name: Run E2E tests
        run: make e2e-test
